### ISSUE TITLE
media query

### ISSUE THREAD

**Issue by wtayyeb** [chuckcarpenter/REM-unit-polyfill#60]
Hi,

Why this polyfill not fixing rems inside media queries?
I know media queries are not supported in IE6-8 but great polyfills exists to solve that like https://github.com/scottjehl/Respond/

I think you could check if that polyfill or simillars are exist or check browser support for media-queries then do rem2px exchange in stylesheets.

Thanks

**Comment by chuckcarpenter** [comment]
@wtayyeb we'd happily accept a pull request for that type of support, but the decision was made awhile ago to ignore MQ rules when the polyfill was kicked in, since support would only be required at desktop. The discussion for that is here, https://github.com/chuckcarpenter/REM-unit-polyfill/issues/13 (brought up by respond.js) and implementation here: https://github.com/chuckcarpenter/REM-unit-polyfill/pull/20.

**Comment by nbouvrette** [comment]
May I suggest to reconsider not implementing this features? A lot of sites are using "mobile first" which means that using your polyfill and respond.js will render the mobile version of the site.

**Comment by nbouvrette** [comment]
Actually it looks like the fix is pending merge in Respond.js : https://github.com/scottjehl/Respond/pull/302

**Comment by nbouvrette** [comment]
If you ever want to implement this feature in your solution, please look at my solution which required a custom Respondjs : https://github.com/nbouvrette/remPolyfill (but please also fix the open issues).
